language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

  
before_script:
  - composer self-update
  - composer require laravel/framework:~4.0
  - composer require phpunit/phpunit:~3.0
  - composer require phpunit/php-invoker:dev-master
  - composer require mockery/mockery:dev-master@dev
  - composer install --prefer-source --no-interaction --dev 
  - composer update

script: phpunit --verbose

matrix:
  allow_failures:
    - php: hhvm
