language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

  
before_script:
  - mysql -e 'create database devdb;'
  - composer self-update
  - composer install --prefer-source --no-interaction --dev 
  - composer update
  
script: phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
