language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm


env:
  - DB=mysql
  
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  #- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS devdb;" -uroot; fi  

#script: phpunit
